name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install and upgrade pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools wheel

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version  # Verify installation
        env:
          POETRY_HOME: ~/.poetry
        continue-on-error: false

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run Black
        run: |
          poetry run black . --check

      - name: Run Tests
        run: |
          poetry run pytest -r P --cov=pygraph

      - name: Generate Docs
        run: |
          poetry run pdoc3 --html pygraph